{
 "title": "Docker Monitoring",
 "tags": [
  "monitoring",
  "linux",
  "bbh",
  "docker"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "agent",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Docker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "System Load" }
   ],
   "targets": [
    {
     "alias": "docker.cpu",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Memory Stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "mem.usage",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "mem.rss",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "mem.cache",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "cache" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "mem.pagefaults",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "pgfault" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Running Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "docker.containers",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Disk Used %" }
   ],
   "targets": [
    {
     "alias": "disk.used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Docker Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "io.rancher.container.ip" ], "type": "tag" },
      { "params": [ "io.rancher.stack.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       { "params": [ "container_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "Container ID" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ]
    }
   ]
  }
 ]
}